name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: YOCKOW/Action-setup-swift@v1
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v --enable-test-discovery
  lint:
    runs-on: ubuntu-lastest
    steps:
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
